name: invoice_ledger
version: "1.0.0"

profile: invoice_ledger

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  invoice_ledger:
    +schema: raw
    raw_invoices:
      +column_types:
        invoice_date: varchar
        due_date: varchar
        total_amount: varchar

models:
  invoice_ledger:
    1_staging:
      +materialized: view
      +schema: staging
    2_intermediate:
      +materialized: view
      +schema: intermediate
    3_marts:
      +materialized: table
      +schema: marts
